## 02.03 - Computation on NumPy Arrays - Universal Functions

Key to do fast computation in NumPy is use **vectorized operations**, generally implemented through **universal functions** (ufuncs).  
The default Python implementation (CPython) is much slower than efficient machine code of languages such as C and Fortran.   
This is particularly evident in _repeated_ operations, such as loops.

In [2]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
        
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [3]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

4.93 s ± 675 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## Universal Functions (UFuncs)

**Vectorized operations** are statically typed, compiled mathematical operations on a sequence of (homogeneous) data.  Due to compuration happening at a lower layer, the execution time is much shorter. 

In [4]:
%timeit (1.0 / big_array) # check out the difference!

11.2 ms ± 1.39 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


Vectorized operations are implemented via <code>ufuncs</code>, whose main purpose is to quickly execute repeated operations on values in NumPy arrays.  

They can work for operations between a scalar and an array (_as above_), but also between two arrays of one or more dimensions.

In [8]:
x = np.arange(12).reshape((3,4))
x ** 3

array([[   0,    1,    8,   27],
       [  64,  125,  216,  343],
       [ 512,  729, 1000, 1331]], dtype=int32)

<code>ufuncs</code> can be <code>unary</code>, operating on **single input**, or <code>binary</code>, operating on **two inputs**.

### Array arithmetic

For arithmetic, we can use the standard Python operators.

In [10]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division
print("-x     = ", -x)     # negation
print("x ** 2 = ", x ** 2) # exponentiation
print("x % 2  = ", x % 2)  # module

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


Combinations of multiple operations can be performed, following the standard order of operations:

In [19]:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

Under the hood, each of these operators is simply a wrapper for a built-in NumPy function (e.g. <code>+</code> = <code>add</code>).  

Here is a list with the full operators functions:

<pre> 
+ 	np.add 	        Addition (e.g., 1 + 1 = 2)
- 	np.subtract 	   Subtraction (e.g., 3 - 2 = 1)
- 	np.negative 	   Unary negation (e.g., -2)
* 	np.multiply 	   Multiplication (e.g., 2 * 3 = 6)
/ 	np.divide 	     Division (e.g., 3 / 2 = 1.5)
//   np.floor_divide     Floor division (e.g., 3 // 2 = 1)
** 	np.power 	     Exponentiation (e.g., 2 ** 3 = 8)
% 	np.mod 	        Modulus/remainder (e.g., 9 % 4 = 1)
</pre>

### Absolute Value

Similarly, **absolute value** is available with the ufuncs <code>absolute</code> and the shorter alis <code>abs</code>:

In [21]:
np.absolute(x)

array([0, 1, 2, 3])

In [22]:
np.abs(x+2)

array([2, 3, 4, 5])

Additionally, this ufunc can handle **complex data**, in which the absolute value returns the magnitude:

In [30]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

### Trigonometric functions

In [31]:
theta = np.linspace(0, np.pi, 3)

In [32]:
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


**Note**: values are computed to within machine precision, which is why values that should be zero do not always hit exactly zero.

Inverse trig functions are also available:

In [34]:
x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


### Exponentials and Logarithms

In [43]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))     # only exp2 
print("3^x   =", np.power(2, x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [2 4 8]


Logarithms are available in 3 flavours: natural, base 2 and base 10.

In [44]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


There are also some specialized versions that are useful for maintaining precision with **very small input**:

In [45]:
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


More **specialized functions** can be found in the submodule <code>scipy.special</code>:

In [47]:
from scipy import special

In [48]:
# Gamma functions (generalized factorials) and related functions
x = [1, 5, 10]
print("gamma(x)     =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2)   =", special.beta(x, 2))

gamma(x)     = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| = [ 0.          3.17805383 12.80182748]
beta(x, 2)   = [0.5        0.03333333 0.00909091]


### Advanced Ufunc Features

For large calculations, can be advantageous specify the **array where we want the result of the calculation** to be stored.  

This can be done using the <code>out</code> argument:

In [50]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 15, out=y)
print(y)

[ 0. 15. 30. 45. 60.]


We can even specify at which parts of the array to write the results:

In [52]:
y = np.zeros(10)
np.power(2, x, out=y[::2]) # write every other element of array y 
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


Another useful advanced function is <code>reduce</code>, which **performs a given operation until only a single result remains**:

In [78]:
x = np.arange(1, 11)
np.add.reduce(x)

55

In [74]:
y = np.arange(1, 5)
np.multiply.reduce(y)   # basically a factorial

24

To store all the intermediate results, simply use <code>accumulate</code>:

In [71]:
np.multiply.accumulate(y)

array([ 1,  2,  6, 24], dtype=int32)

Finally, ufuncs can compute the output of all pairs of two different inputs using the <code>outer</code> method: 

In [79]:
np.multiply.outer(x,y)

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16],
       [ 5, 10, 15, 20],
       [ 6, 12, 18, 24],
       [ 7, 14, 21, 28],
       [ 8, 16, 24, 32],
       [ 9, 18, 27, 36],
       [10, 20, 30, 40]])