# 02.02 - Basics of NumPy Arrays

Basic categories of array manipulation:

1. **Attributes**: Determining the size, shape, memory consumption, and data types of arrays
2. **Indexing**: Getting and setting the value of individual array elements
3. **Slicing**: Getting and setting smaller subarrays within a larger array
4. **Reshaping**: Changing the shape of a given array
5. **Joining and splitting**: Combining multiple arrays into one, and splitting one array into many

### 1. NumPy Array Attributes

Let's start by defining three random arrays: one-dimensional, two-dimensional, and three-dimensional.

In order to ensure that the same random arrays are generated each time the code is run, we can specificy a set _seed_ in NumPy random number generator.

In [1]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

For each array, we can find, among the others:

* <code>ndim</code>: number of dimensions  
* <code>shape</code>: size of each dimension  
* <code>size</code>: total size of array (in terms of num of elements)  
* <code>itemsize</code>: total size of _each_ array (in bytes)
* <code>nbytes</code>: total size of the array (in bytes)
* <code>dtype</code>: data type  
    
For example, using our two-dimensional array:

In [2]:
print('x2 num_dim: ', x2.ndim)
print('x2 shape:', x2.shape)
print('x2 size: ', x2.size)
print('x2 item_size: ', x2.itemsize, 'bytes')
print('x2 num_bytes: ', x2.nbytes, 'bytes')
print('x2 data type: ', x2.dtype)

x2 num_dim:  2
x2 shape: (3, 4)
x2 size:  12
x2 item_size:  4 bytes
x2 num_bytes:  48 bytes
x2 data type:  int32


As a general rule, <code>nbytes</code> = <code>itemsize</code> * <code>size</code>

### 2. Array Indexing 

For one-dimensional arrays, indexing is similar to Python:

In [3]:
x1

array([5, 0, 3, 3, 7, 9])

In [4]:
x1[0] # First value

5

In [5]:
x1[1] # Third value

0

In [6]:
x1[-1]# Last value

9

In [7]:
x1[-2]# Penultimate value

7

For multi-dimensional arrays, items can be accessed with a (row, col) tuple:

In [8]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [9]:
x2[2,3]

7

In [10]:
x2[-1,-3]

6

To modify arrays, we can specify the index to replace:

In [11]:
x2[2,3] = 8

In [12]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 8]])

**Note**: NumPy arrays are fixed type, so e.g. a floating point will be truncated (3.14 > 3)

### 3. Array Slicing

Once again, NumPy follows the standard Python notation: <code>x[start:stop:step]</code> with default values:  

* <code>start</code> = 0
* <code>stop</code> = size of dimension
* <code>step</code> = 1

**Note**: with a negative <code>step</code> value, <code>start</code> and <code>stop</code> are swapped. This is convenient to swap an array.

In [13]:
x = np.arange(15)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
x[::-1] # Reverse the array

array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [15]:
x[10::-2] # Reverse from index 10 with step 2

array([10,  8,  6,  4,  2,  0])

For multi-dimensional arrays we can get subarrays with multiple slices separated by commas. For example:

In [16]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 8]])

In [17]:
x2[:2, :3] # 2 rows, 3 cols

array([[3, 5, 2],
       [7, 6, 8]])

In [18]:
x2[:3, ::2] # 3 rows, every other column

array([[3, 2],
       [7, 8],
       [1, 7]])

In [ ]:
x2[::-1, ::-1] # Reverse array